const TETROMINOES = {
  I: [
    [
      [Playfield.FILLED],
      [Playfield.FILLED],
      [Playfield.FILLED],
      [Playfield.FILLED]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED,Playfield.FILLED,Playfield.FILLED]
    ],
    [
      [Playfield.FILLED],
      [Playfield.FILLED],
      [Playfield.FILLED],
      [Playfield.FILLED]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED,Playfield.FILLED,Playfield.FILLED]
    ]
  ],
  J: [
    [
      [Playfield.EMPTY,Playfield.FILLED],
      [Playfield.EMPTY,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED,Playfield.FILLED],
      [Playfield.EMPTY,Playfield.EMPTY,Playfield.FILLED]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.EMPTY],
      [Playfield.FILLED,Playfield.EMPTY]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED,Playfield.FILLED],
      [Playfield.EMPTY,Playfield.EMPTY,Playfield.FILLED]
    ]
  ],
  L: [
    [
      [Playfield.FILLED,Playfield.EMPTY],
      [Playfield.FILLED,Playfield.EMPTY],
      [Playfield.FILLED,Playfield.FILLED]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.EMPTY,Playfield.EMPTY]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.EMPTY,Playfield.FILLED],
      [Playfield.EMPTY,Playfield.FILLED]
    ],
    [
      [Playfield.EMPTY,Playfield.EMPTY,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED,Playfield.FILLED]
    ]
  ],
  O: [
    [
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED]
    ]
  ],
  S: [
    [
      [Playfield.EMPTY,Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED,Playfield.EMPTY]
    ],
    [
      [Playfield.FILLED,Playfield.EMPTY],
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.EMPTY,Playfield.FILLED]
    ],
    [
      [Playfield.EMPTY,Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED,Playfield.EMPTY]
    ],
    [
      [Playfield.FILLED,Playfield.EMPTY],
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.EMPTY,Playfield.FILLED]
    ]
  ],
  T: [
    [
      [Playfield.FILLED,Playfield.FILLED,Playfield.FILLED],
      [Playfield.EMPTY,Playfield.FILLED,Playfield.EMPTY]
    ],
    [
      [Playfield.EMPTY,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.EMPTY,Playfield.FILLED]
    ],
    [
      [Playfield.EMPTY,Playfield.FILLED,Playfield.EMPTY],
      [Playfield.FILLED,Playfield.FILLED,Playfield.FILLED]
    ],
    [
      [Playfield.FILLED,Playfield.EMPTY],
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.EMPTY]
    ]
  ],
  Z: [
    [
      [Playfield.FILLED,Playfield.FILLED,Playfield.EMPTY],
      [Playfield.EMPTY,Playfield.FILLED,Playfield.FILLED]
    ],
    [
      [Playfield.EMPTY,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.EMPTY]
    ],
    [
      [Playfield.FILLED,Playfield.FILLED,Playfield.EMPTY],
      [Playfield.EMPTY,Playfield.FILLED,Playfield.FILLED]
    ],
    [
      [Playfield.EMPTY,Playfield.FILLED],
      [Playfield.FILLED,Playfield.FILLED],
      [Playfield.FILLED,Playfield.EMPTY]
    ]
  ]
};
